In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 5.07 ms, sys: 5.43 ms, total: 10.5 ms
Wall time: 8.27 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 134 ms, sys: 33.3 ms, total: 167 ms
Wall time: 169 ms


In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[ 0.09230528,  0.71468293, -0.71728517],
       [ 0.06524521, -1.93318252, -0.21630382]])

In [8]:
data * 10

array([[  0.92305284,   7.1468293 ,  -7.17285167],
       [  0.65245214, -19.33182516,  -2.16303822]])

In [9]:
data +data 

array([[ 0.18461057,  1.42936586, -1.43457033],
       [ 0.13049043, -3.86636503, -0.43260764]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6,7.5,8,0,1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int64')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [27]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
arr = np.array([1,2,3,4,5])

In [31]:
arr.dtype

dtype('int64')

In [32]:
float_arr = arr.astype(np.float64)

In [33]:
float_arr.dtype

dtype('float64')

In [34]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [35]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [36]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [37]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [38]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [39]:
int_array = np.arange(10)

In [40]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [41]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [42]:
empty_uint32 = np.empty(8, dtype='u4')

In [43]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [45]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [46]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr *arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
arr ** .5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [52]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

In [53]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [54]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [55]:
arr = np.arange(10)

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[5]

5

In [58]:
arr[5:8]

array([5, 6, 7])

In [59]:
arr[5:8] = 12

In [60]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [62]:
arr_slice = arr[5:8]

In [63]:
arr_slice

array([12, 12, 12])

In [64]:
arr_slice[1] =12345

In [65]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [66]:
arr_slice[:] = 64

In [67]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [68]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [69]:
arr2d[2]

array([7, 8, 9])

In [70]:
arr2d[0][2]

3

In [71]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [72]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
old_values = arr3d[0].copy()

In [75]:
arr3d[0] = 42

In [76]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0] = old_values

In [78]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[1, 0]

array([7, 8, 9])

In [80]:
x = arr3d[1]

In [81]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [82]:
x[0]

array([7, 8, 9])

In [83]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [84]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [85]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [88]:
arr2d[1, :2]

array([4, 5])

In [89]:
arr2d[:2, 2]

array([3, 6])

In [90]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [91]:
arr2d[:2, 1:] =0

In [92]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [93]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [94]:
data = np.random.randn(7, 4)

In [95]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [ ]:
data

In [97]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [101]:
data[names == 'Bob']

array([[-0.57759429, -1.11550534,  2.45457495,  0.36763937],
       [-1.33832724,  2.63890193, -0.01854087,  0.42866991]])

In [102]:
data[names == 'Bob', 2:]

array([[ 2.45457495,  0.36763937],
       [-0.01854087,  0.42866991]])

In [103]:
data[names == 'Bob', 3:]

array([[0.36763937],
       [0.42866991]])

In [104]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [107]:
data[~(names == 'Bob')]

array([[ 1.18120955,  0.37039988, -1.35238672, -0.02966236],
       [ 0.09000931,  0.22537913,  1.01587728, -0.06852347],
       [ 0.02324827,  0.09944101,  0.11117165,  2.39479932],
       [-0.37066522, -0.73692423, -1.21495122, -1.37778937],
       [ 0.09942449,  0.60397309,  0.6084966 , -0.78894256]])

In [108]:
cond = names == 'Bob'

In [109]:
data[~cond]

array([[ 1.18120955,  0.37039988, -1.35238672, -0.02966236],
       [ 0.09000931,  0.22537913,  1.01587728, -0.06852347],
       [ 0.02324827,  0.09944101,  0.11117165,  2.39479932],
       [-0.37066522, -0.73692423, -1.21495122, -1.37778937],
       [ 0.09942449,  0.60397309,  0.6084966 , -0.78894256]])

In [110]:
mask = (names == 'Bob') | (names == 'Will')

In [111]:
mask

array([ True, False,  True,  True,  True, False, False])

In [112]:
data[mask]

array([[-0.57759429, -1.11550534,  2.45457495,  0.36763937],
       [ 0.09000931,  0.22537913,  1.01587728, -0.06852347],
       [-1.33832724,  2.63890193, -0.01854087,  0.42866991],
       [ 0.02324827,  0.09944101,  0.11117165,  2.39479932]])

In [113]:
data[data < 0] =0

In [114]:
data

array([[0.        , 0.        , 2.45457495, 0.36763937],
       [1.18120955, 0.37039988, 0.        , 0.        ],
       [0.09000931, 0.22537913, 1.01587728, 0.        ],
       [0.        , 2.63890193, 0.        , 0.42866991],
       [0.02324827, 0.09944101, 0.11117165, 2.39479932],
       [0.        , 0.        , 0.        , 0.        ],
       [0.09942449, 0.60397309, 0.6084966 , 0.        ]])

In [115]:
data[names != 'Joe'] =7

In [116]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.18120955, 0.37039988, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.09942449, 0.60397309, 0.6084966 , 0.        ]])

In [117]:
arr = np.empty((8,4))

In [118]:
for i in range(8):
    arr[i] = i

In [119]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [120]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [121]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [122]:
arr = np.arange(32).reshape((8,4))

In [123]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [124]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [125]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])