In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
my_arr = np.arange(1000000)

In [7]:
my_list = list(range(1000000))

In [9]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 8.75 ms, sys: 10.8 ms, total: 19.6 ms
Wall time: 18.1 ms


In [10]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 146 ms, sys: 37.8 ms, total: 183 ms
Wall time: 187 ms


In [11]:
data = np.random.randn(2, 3)

In [12]:
data

array([[-0.45225903,  2.27454544, -0.06640469],
       [-0.59577585, -0.43640601, -0.97982258]])

In [13]:
data * 10

array([[-4.52259032, 22.7454544 , -0.66404691],
       [-5.95775851, -4.36406006, -9.79822576]])

In [14]:
data +data 

array([[-0.90451806,  4.54909088, -0.13280938],
       [-1.1915517 , -0.87281201, -1.95964515]])

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

In [21]:
data1 = [6,7.5,8,0,1]

In [22]:
arr1 = np.array(data1)

In [23]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [24]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [25]:
arr2 = np.array(data2)

In [26]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr2.ndim

2

In [28]:
arr2.shape

(2, 4)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int64')

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [36]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [37]:
arr1.dtype

dtype('float64')

In [43]:
arr2.dtype

dtype('int32')

In [48]:
arr = np.array([1,2,3,4,5])

In [49]:
arr.dtype

dtype('int64')

In [50]:
float_arr = arr.astype(np.float64)

In [51]:
float_arr.dtype

dtype('float64')

In [52]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [53]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [54]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [55]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [56]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [57]:
int_array = np.arange(10)

In [58]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [59]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
empty_uint32 = np.empty(8, dtype='u4')

In [61]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)